// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz0of1zIqPB0y8gq2pVjAfsWoqnaNUkXE',
    appId: '1:311080639350:web:64c8c85be33a13d3af7857',
    messagingSenderId: '311080639350',
    projectId: 'stajuygulamasi-86373',
    authDomain: 'stajuygulamasi-86373.firebaseapp.com',
    storageBucket: 'stajuygulamasi-86373.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSC2ZK6ufAfhli_l_TdWiN3IosYbum1co',
    appId: '1:311080639350:android:040b71c6cc3f0d65af7857',
    messagingSenderId: '311080639350',
    projectId: 'stajuygulamasi-86373',
    storageBucket: 'stajuygulamasi-86373.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7xRKrovQDuuVbhCsBwOpAH-2cimW22f8',
    appId: '1:311080639350:ios:b88c4aa29e0ba414af7857',
    messagingSenderId: '311080639350',
    projectId: 'stajuygulamasi-86373',
    storageBucket: 'stajuygulamasi-86373.appspot.com',
    iosBundleId: 'com.pn6.etkinlikuygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7xRKrovQDuuVbhCsBwOpAH-2cimW22f8',
    appId: '1:311080639350:ios:b88c4aa29e0ba414af7857',
    messagingSenderId: '311080639350',
    projectId: 'stajuygulamasi-86373',
    storageBucket: 'stajuygulamasi-86373.appspot.com',
    iosBundleId: 'com.pn6.etkinlikuygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz0of1zIqPB0y8gq2pVjAfsWoqnaNUkXE',
    appId: '1:311080639350:web:6cd57a61a1581e2eaf7857',
    messagingSenderId: '311080639350',
    projectId: 'stajuygulamasi-86373',
    authDomain: 'stajuygulamasi-86373.firebaseapp.com',
    storageBucket: 'stajuygulamasi-86373.appspot.com',
  );
}
